site_name: Prof. José W. R. Pereira

nav:
  - Principal:
      - index.md
      - Sistemas Digitais: index_digitais.md
      - Automação Industrial: index_automacao.md
      - Ciência de Dados: index_dados.md
      - Projetos: index_gestao.md
      - IFSP-Salto:
          - index_ifsp_slt.md
          - 2026:
              - SLTSDIG:
                  - ifsp-slt/digitais/sltsdig_ementa.md
                  - ifsp-slt/digitais/sltsdig_plano_aula.md
              - SLTCLPE:
                  - ifsp-slt/automacao/sltclpe_ementa.md
                  - ifsp-slt/automacao/sltclpe_plano_aula.md
              - SLTMCMP:
                  - ifsp-slt/digitais/sltmcmp_ementa.md
                  - ifsp-slt/digitais/sltmcmp_plano_aula.md
          - 2025:
              - SDPE8:
                  - ifsp-slt/sdpe8.md
                  - ifsp-slt/vhdl/lista1.md
                  - ifsp-slt/vhdl/lista2.md
                  - ifsp-slt/vhdl/lista3.md
                  - ifsp-slt/vhdl/lista4.md
              - RPIE8:
                  - ifsp-slt/rpie8.md
                  - ifsp-slt/redes/lab04.md
                  - ifsp-slt/redes/lab05.md
                  - ifsp-slt/redes/lab06.md
              - CLPR:
                  - ifsp-slt/sltclpr.md
              - SAUT:
                  - ifsp-slt/saut/lista1.md
  - Sistemas Digitais:
      - index_digitais.md
      - Tecnologia:
          - Eletrônica Digital:
              - digitais/Tecnologia/eletronicaDigital/sdig0-fundamentos.md
              - digitais/Tecnologia/eletronicaDigital/sdig1-sistema_numeracao.md
              - digitais/Tecnologia/eletronicaDigital/sdig2-portas_logicas.md
              - digitais/Tecnologia/eletronicaDigital/sdig3-expressoes_logicas_circuitos.md
              - digitais/Tecnologia/eletronicaDigital/sdig4-mapa_de_karnaugh.md
          - Microcontroladores:
              - digitais/Tecnologia/mcu/mcu1-embarcados.md
              - digitais/Tecnologia/mcu/mcu2-microcontroladores.md
              - digitais/Tecnologia/mcu/mcu3-perifericos_internos.md
              - digitais/Tecnologia/mcu/mcu4-simuladores.md
              - digitais/Tecnologia/mcu/mcu5-frameworks.md
          - FPGA:
              - digitais/Tecnologia/fpga/tecnologia/t01-intro_plds.md
              - digitais/Tecnologia/fpga/tecnologia/t02-terasic-DE1-SoC.md
              - digitais/Tecnologia/fpga/tecnologia/t03-quartus-novo_projeto.md
              - digitais/Tecnologia/fpga/tecnologia/t04-quartus-sim_vwf.md
              - digitais/Tecnologia/fpga/tecnologia/t05-quartus-rtl_viewer.md
              - digitais/Tecnologia/fpga/tecnologia/t06-ghdl-gtkwave.md
      - Controladores:
          - Arduino:
              - digitais/Controladores/arduino/uno01-digital_output.md
              - digitais/Controladores/arduino/uno02-digital_input.md
          - AVR ATmega328P:
              - digitais/Controladores/avr_atmega328p/avr00-devTools.md
              - digitais/Controladores/avr_atmega328p/avr01-digital_io.md
#              - digitais/mcu/avr_atmega328p/lab00-ambientacao.md
#              - digitais/mcu/avr_atmega328p/lab01-sinalizador_garagem.md
#              - digitais/mcu/avr_atmega328p/lab02-partida_estrela_triangulo.md
#              - digitais/mcu/avr_atmega328p/lab03-semaforo.md
#              - digitais/mcu/avr_atmega328p/lab04-display7seg.md
#              - digitais/mcu/avr_atmega328p/lab05-2displays7seg.md
#              - digitais/mcu/avr_atmega328p/lab06-deteccao_bordas.md
              - digitais/mcu/avr_atmega328p/lab07-bibliotecas.md
#              - digitais/mcu/avr_atmega328p/lab08-semaforo_temporizado.md
#              - digitais/mcu/avr_atmega328p/lab09-displayLCD.md
              - digitais/mcu/avr_atmega328p/lab10-teclado.md
              - digitais/mcu/avr_atmega328p/lab11-ihm.md
              - digitais/mcu/avr_atmega328p/lab12-timer.md
              - digitais/mcu/avr_atmega328p/lab13-adc.md
              - digitais/mcu/avr_atmega328p/lab14-usart.md
#              - digitais/mcu/avr_atmega328p/lab_atividades.md
          - ESP32:
              - digitais/iot/esp32/esp32-1-intro.md
              - digitais/iot/esp32/lab00-ambientacao.md
              - digitais/iot/esp32/lab01-blink.md
              - digitais/iot/esp32/lab02-componente.md
      - Periféricos:
          - Digital I/O:
              - digitais/Perifericos/dio01-led.md
              - digitais/Perifericos/dio02-button.md
              - digitais/Perifericos/dio03-display7seg.md
              - digitais/Perifericos/dio04-displayLCD.md
              - digitais/Perifericos/dio05-teclado.md
      - Placa de Circuito Impresso:
          - Tecnologia:
              - digitais/PCI/Tecnologia/1-PCI.md
          - KiCad:
              - digitais/PCI/KiCad/1-KiCad.md
              - digitais/PCI/KiCad/2-Novo_Projeto.md
              - digitais/PCI/KiCad/3-Esquematico.md
      - Situações de Aprendizagem:
          - Básicas:
              - digitais/SituacoesAprendizagem/Basicas/sa01-sinalizador_garagem.md
              - digitais/SituacoesAprendizagem/Basicas/sa02-partida_estrela_triangulo.md
              - digitais/SituacoesAprendizagem/Basicas/sa03-semaforo.md
              - digitais/SituacoesAprendizagem/Basicas/sa04-semaforo_temporizado.md
              - digitais/SituacoesAprendizagem/Basicas/sa05-displayLCD.md
          - Intermediárias:
              - digitais/SituacoesAprendizagem/Intermediarias/01-ihm.md

  - Automação Industrial:
      - index_automacao.md
      - Tecnologia:
          - Controladores Programáveis:
              - automacao/clp/tecnologia/01-fundamentos.md
              - automacao/clp/tecnologia/02-interfaces.md
              - automacao/clp/tecnologia/03-num_logicas.md
              - automacao/clp/tecnologia/04-acionamento_basico.md
          - Redes Industriais:
              - automacao/redes/tecnologia/01-redes_conceito.md
              - automacao/redes/tecnologia/02-classificacao_arquiteturas.md
              - automacao/redes/tecnologia/03-dimensionamento.md
              - automacao/redes/tecnologia/04-modelo_osi_iso.md
              - automacao/redes/tecnologia/05-meio_fisico.md
              - automacao/redes/tecnologia/06-protocolos_comunicacao.md
              - automacao/redes/tecnologia/07-wireless.md
              - automacao/redes/tecnologia/08-iiot.md
          - SCADA:
              - automacao/scada/tecnologia/01-conceito.md
              - automacao/scada/tecnologia/02-scada_br.md
              - automacao/scada/tecnologia/03-scada_br_lab.md
      #      - Pneumática:
      #          - Simulação:
      #              - automacao/pneumatica/fluidsim/01-simulacao.md
      #              - automacao/pneumatica/fluidsim/02-circuitosSequenciais.md
      - Equipamento:
          - Altus Duo TB131:
              - automacao/clp/altus_tb131/lab00-ambientacao.md
              - automacao/clp/altus_tb131/lab01-novo_projeto.md
              - automacao/clp/altus_tb131/lab02-contatos_bobinas.md
              - automacao/clp/altus_tb131/lab03-setReset.md
              - automacao/clp/altus_tb131/lab04-borda_subida_descida.md
              - automacao/clp/altus_tb131/lab05-temporizadores.md
              - automacao/clp/altus_tb131/lab06-contadores.md
              - automacao/clp/altus_tb131/lab07-blocos_funcionais.md
              - automacao/clp/altus_tb131/lab08-entradas_saidas_analogicas.md
              - automacao/clp/altus_tb131/lab09-bloco_funcional.md
              - automacao/clp/altus_tb131/lab10-funcao.md
      - Situações de Aprendizagem:
          - CLP:
              - automacao/sitap/clp/sa1-operacoes_logicas.md
              - automacao/sitap/clp/sa2-projeto_partida_direta_motor.md
              - automacao/sitap/clp/sa3-projeto_portao_diretaReversao.md
              - automacao/sitap/clp/sa4-projeto_partida_estrela_triangulo.md
              - automacao/sitap/clp/sa5-projeto_semaforo.md

  - Ciência de Dados:
      - index_dados.md
      - Dados:
          - Análise de Dados:
              - dados/ad/ad00-analise_de_dados.md
              - dados/ad/ad01-ambiente_desen.md
              - dados/ml/ml02-ml.md
              - dados/ml/ml03-matriz_confusao.md
              - dados/ml/ml04-knn.md
              - dados/ml/ml05-regressao_linear.md
              - dados/ml/ml06-k_means.md
              - dados/ml/ml07-rede_neural.md
          - Machine Learning:
              - dados/ml/ml01-ia_ml_dl.md
              - dados/ml/ml02-intro.md
              - dados/ml/ml03-fundamento_classificacao.md
  #              - dados/ml/ml08-fuzzy.md
  - Projetos:
      - index_gestao.md
      - gestao/git.md




  - Indicações:
      - indicacoes.md

#        - automacao\clp\altus_tb131\h1_10_1-ihm_display_var.md
#        - automacao\clp\altus_tb131\h1_10_2-ihm_edita_var.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: pt-BR
  logo: assets/logo.png
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: orange
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: orange
  font:
    text: Lora
    code: Roboto Mono

#    plugins:
#      - blog:
#        blog_dir: blog
#        blog_toc: true
#        post_date_format: full
#        post_url_date_format: yyyy/MM/dd
#        archive: false

repo_url: https://github.com/josewrpereira/docs
repo_name: josewrpereira/docs

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/josewrpereira
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/josewrpereira/
    - icon: fontawesome/solid/envelopes-bulk
      link: mailto:josewrpereira@protonmail.com

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

copyright: |
  &copy; 2026 <a href="https://github.com/josewrpereira" target="_blank" rel="noopener">José W. R. Pereira</a>
